### ISSUE TITLE
Mining pools don't seem to work

### ISSUE THREAD

**Issue by screab-idh** [hempcoin-project/THC#10]
Hi,

I tried to get to a mining pool for hempcoin but from the 4 advertised websites 1 is down, 1 domain is for sale, 1 sells news about hemp and 1 stucks at loading ( so probably down ).

Could we get some updated info about the community around hempcoin ?

**Comment by hempcoin-project** [comment]
Hi. Look at the last pages or bitcointalk. I think there is a pool listed there. 

Tim Renzetti
256.759.0161
