### ISSUE TITLE
THC wallet ERROR

### ISSUE THREAD

**Issue by btceugen** [hempcoin-project/THC#13]
DEAR ALL, i am looking for help. My THC wallet does not load anymore, it always shows error message

File: crs/kernel.cpp, Line 430 

Expression: pindex-> pprev pindex->GetBlockHash() = = (!fTestNet ? hashGenesisBlock : hashGenesisBlockTestNet)

Do you have any idea how to fix this?

**Comment by plasmacorral** [comment]
This is the larger section of code to get stake modifier checksum, but not sure what is causing your issue.  

Have you looked for any logs to see if they provide any more meaningful error messages?

// Get stake modifier checksum
unsigned int GetStakeModifierChecksum(const CBlockIndex* pindex)
{
    assert (pindex->pprev || pindex->GetBlockHash() == (!fTestNet ? hashGenesisBlock : hashGenesisBlockTestNet));
    // Hash previous checksum with flags, hashProofOfStake and nStakeModifier
    CDataStream ss(SER_GETHASH, 0);
    if (pindex->pprev)
        ss << pindex->pprev->nStakeModifierChecksum;
    ss << pindex->nFlags << pindex->hashProofOfStake << pindex->nStakeModifier;
    uint256 hashChecksum = Hash(ss.begin(), ss.end());
    hashChecksum >>= (256 - 32);
    return hashChecksum.Get64();
}

**Comment by 0xfff** [comment]
what version is your wallet?

**Comment by withthelemons** [comment]
This is probably fixed already, I'm gonna close it.
