### ISSUE TITLE
Tooltip background on "Your crop" page is black

### ISSUE THREAD

**Issue by hempcoin-project** [hempcoin-project/THC#3]

**Comment by withthelemons** [comment]
Doesn't occur anymore with HempCoin 2.0 and Qt 5.7

**Comment by hempcoin-project** [comment]
My friend (with the lemons). Are you in contact with the coder?  Wasn't sure if you were communicating with the coder

Tim Renzetti
256.759.0161

**Comment by withthelemons** [comment]
No, I'm not.

**Comment by hempcoin-project** [comment]
Hit me up on skype: AUTOVID

 

What do you think about the latest wallet?

 

 

 

Tim Renzetti

256.759.0161

**Comment by withthelemons** [comment]
I think it's very good
