### ISSUE TITLE
HempCoin Advocate Needs Contact With Coin Creator!

### ISSUE THREAD

**Issue by SativaYoga** [hempcoin-project/THC#8]
Hello $THC Team!

* **[I believe in HempCoin](https://steemit.com/cryptocurrency/@erikaharris/hempcoin-usdthc-series-2-needed-visionary-crypto-developers)**.

* I believe it is MORE than a digital currency.

* I believe it has the seed-potential to RESTORE THE HEALTH of our (1) bodies, (2) minds, (3) soil, (4) air and (5) economics.

**The heartiest plant on earth, deserves to be paired with the heartiest coin on earth!**

I want to see that happen. I want to help make that happen. But I need to speak with someone who has technical prowess, and is willing to at least hear out an audacious vision that PUSHES THE CAPACITY of this coin!

I have been earnestly trying to reach the creator of HempCoin, because I have not identified a formidable coin competitor of yours. But, man, the unresponsiveness almost makes me wish that wasn't the case!

I've reached out on Twitter, Bitcoin Forum, Steemit and Email. GitHub is now the 5th platform on which I have said, _"I am here to support and herald you! With great loyalty and enthusiasm! Can someone on the team please talk with me?"_

Crickets.

I know life is fast and full, but it really shouldn't be this hard to help...

**Comment by hempcoin-project** [comment]
Hello,

I am Tim the creator of HempCoin THC. We are always interested in helping projects. You are welcome to call me. Skype: Autovid or text me 256.759.0161 anytime. 

Regards,

Tim Renzetti
256.759.0161

**Comment by SativaYoga** [comment]
Thank you so much for replying, Tim!

I am in Acapulco, Mexico, and we are currently undergoing a major storm system. I keep losing electricity and internet. That's the only reason you didn't get a call from me right away!

I couldn't help but promote and invest in $THC as soon as I saw it... because it touches the core of my greatest values.

So I'm here to promote HempCoin from integrity and passion. 💚🌿

You are the coin's creator, and I'd like to collaborate with you. 

I was already committed to cannabis/hemp as a personal mission  (www.patreon.com/sativayoga), so promoting HempCoin just feels like a natural extension of that advocacy.

I'd love to have your official blessing for me to carry on singing the praises of HempCoin to the world.

Also, may I interview you, Tim? Briefly. Under 20 minutes (though you're welcome to share for longer if you like.) We could do side-by-side video on Zoom. Will be fantastic, and I'd promote everywhere.

The coin needs your face, Tim. And with yesterday's spike🚀, $THC is fresh on everyone's minds.

Let's take advantage of that! What do you think? 

Excited! ✨
Erika Harris
Skype ID: empathicwriter 
Skype #: 312-488-1064 <--- Haven't used yet, fyi, but should be fine.
